name:  pakage to docker
on: 
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # vite 打包
      - name: Install dependencies
        run: cd fcb-fronted && npm install && npm run build
      # 返回根目录
      - name: Return to root
        run: cd ..
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the Docker image
        run: docker build --file Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/filecodebox:latest .
      - name: Docker image push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/filecodebox:latest
      - name: 更新服务器
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }} # 服务器ip地址 ; 需要去仓库的 settings/secrets/actions 去创建
          username: ${{ secrets.SERVER_USER }} # 服务器用户名称；需要去仓库的 settings/secrets/actions 去创建
          password: ${{ secrets.SERVER_PWD }} # 服务器密码；需要去仓库的 settings/secrets/actions 去创建
          port: ${{ secrets.SERVER_PORT }} # 服务器端口，默认22；需要去仓库的 settings/secrets/actions 去创建
          script: | # 重启更新镜像
            if docker ps -a | grep -q 'myfilebox'; then
              docker stop myfilebox
              docker rm myfilebox 
            fi
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }} --password-stdin
            docker pull liuyaowen0925/filecodebox:latest 
            docker run -dp 1212:12345  --restart=always --name myfilebox liuyaowen0925/filecodebox:latest